title: Lab 9
remote_theme: just-the-docs/just-the-docs

nav_external_links:
  - title: 1. Install kafka
    url: lab9%20stream_data_pipeline_1.html#1-install-kafka
  - title: 2. Sending messages between producer and consumers in Kafka
    url: lab9%20stream_data_pipeline_1.html#2-sending-messages-between-producer-and-consumers-in-kafka
  - title: 3. Scenario Streaming audio
    url: lab9%20stream_data_pipeline_1.html#3-scenario-streaming-audio
  - title: 3.1 Stream audio data auto-transcription
    url: lab9%20stream_data_pipeline_1.html#31-stream-audio-data-auto-transcription
  - title: 3.1.1 Stream in audio
    url: lab9%20stream_data_pipeline_1.html#311-stream-in-audio
  - title: 3.1.2 Load whisper model once
    url: lab9%20stream_data_pipeline_1.html#312-load-whisper-model-once
  - title: 3.1.3 Read from the script as you are recording
    url: lab9%20stream_data_pipeline_1.html#313-read-from-the-script-as-you-are-recording
  - title: 3.1.4 Capture one sentence
    url: lab9%20stream_data_pipeline_1.html#314-capture-one-sentence
  - title: 3.1.5 Capture a paragraph
    url: lab9%20stream_data_pipeline_1.html#315-capture-a-paragraph
  - title: 3.1.6 Record audio, Transcribe, Translate
    url: lab9%20stream_data_pipeline_1.html#316-record-audio-transcribe-translate
  - title: Conclusion
    url: lab9%20stream_data_pipeline_1.html#conclusion
  - title: Submissions next Wed 9pm (22 Oct 2025)
    url: lab9%20stream_data_pipeline_1.html#submissions-next-wed-9pm-22-oct-2025

just_the_docs:
  custom_css:
    - assets/css/style.scss
    - assets/js/fix-links.js

